### ISSUE TITLE
Empty "self._deck[]" edge case in tier4.py

### ISSUE THREAD

**Issue by AdvitDeepak** [jasonjewik/snape#3]
Got the following after running a few times (seems related to Issue #2 ): 

`AttributeError: 'NoneType' object has no attribute 'attack'`

![image](https://user-images.githubusercontent.com/13698191/149720680-46012b7c-c311-4de3-909f-3628dbfb3089.png)

Error arises in `self._deck[index].attack += self.health` from `tier4.py`.

**Comment by jasonjewik** [comment]
Honestly not sure what could cause this issue without seeing more details on how to reproduce it. After all, line 37 of `food/tier4.py` shouldn't even run if `self._deck[index]` is `None`.

**Comment by jasonjewik** [comment]
Created a new branch that includes changes to `example.py` that should make it easier for us to backtrace errors: https://github.com/jasonjewik/snape/tree/error_handling. Merging this branch into `main` pends on merging `python_env` first.
